// Generated by Classiq.
// Classiq version: 0.105.0
// Creation timestamp: 2026-02-01T03:28:07.696847+00:00
// Random seed: 1082266004

OPENQASM 2.0;
include "qelib1.inc";
gate main__identity q0,q1,q2,q3,q4,q5,q6 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__rygate q0 {
  ry(0.43407392576958137) q0;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_1__gray_code_y q0,q1 {
  ry(0.8780421791460414) q1;
  cx q0,q1;
  ry(0) q1;
  cx q0,q1;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_1__identity_1 q0,q1,q2,q3,q4,q5 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_5__gray_code_y q0,q1,q2 {
  ry(1.201533300068379) q2;
  cx q0,q2;
  ry(0) q2;
  cx q1,q2;
  ry(0) q2;
  cx q0,q2;
  ry(0) q2;
  cx q1,q2;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_5__identity_1 q0,q1,q2,q3,q4 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_9__gray_code_y q0,q1,q2,q3 {
  ry(1.3829347993640035) q3;
  cx q0,q3;
  ry(0) q3;
  cx q1,q3;
  ry(0) q3;
  cx q0,q3;
  ry(0) q3;
  cx q2,q3;
  ry(0) q3;
  cx q0,q3;
  ry(0) q3;
  cx q1,q3;
  ry(0) q3;
  cx q0,q3;
  ry(0) q3;
  cx q2,q3;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_9__identity_1 q0,q1,q2,q3 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_13__gray_code_y q0,q1,q2,q3,q4 {
  ry(1.4764484235195334) q4;
  cx q0,q4;
  ry(0) q4;
  cx q1,q4;
  ry(0) q4;
  cx q0,q4;
  ry(0) q4;
  cx q2,q4;
  ry(0) q4;
  cx q0,q4;
  ry(0) q4;
  cx q1,q4;
  ry(0) q4;
  cx q0,q4;
  ry(0) q4;
  cx q3,q4;
  ry(0) q4;
  cx q0,q4;
  ry(0) q4;
  cx q1,q4;
  ry(0) q4;
  cx q0,q4;
  ry(0) q4;
  cx q2,q4;
  ry(0) q4;
  cx q0,q4;
  ry(0) q4;
  cx q1,q4;
  ry(0) q4;
  cx q0,q4;
  ry(0) q4;
  cx q3,q4;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_13__identity_1 q0,q1,q2 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_17__gray_code_y q0,q1,q2,q3,q4,q5 {
  ry(1.5235697973445805) q5;
  cx q0,q5;
  ry(0) q5;
  cx q1,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q2,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q1,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q3,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q1,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q2,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q1,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q4,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q1,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q2,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q1,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q3,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q1,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q2,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q1,q5;
  ry(0) q5;
  cx q0,q5;
  ry(0) q5;
  cx q4,q5;
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_17__identity_1 q0,q1 {
}

gate inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23__block_wrapper_21__gray_code_y q0,q1,q2,q3,q4,q5,q6 {
  ry(1.5471764760991782) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q2,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q3,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q2,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q4,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q2,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q3,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q2,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q5,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q2,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q3,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q2,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q4,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q2,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q3,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q2,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q1,q6;
  ry(0) q6;
  cx q0,q6;
  ry(0) q6;
  cx q5,q6;
}

qreg q[7];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__rygate q[6];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_1__gray_code_y q[6],q[5];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_3__block_wrapper_1__identity_1 q[0],q[1],q[2],q[3],q[4],q[5];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_5__gray_code_y q[6],q[5],q[4];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_7__block_wrapper_5__identity_1 q[0],q[1],q[2],q[3],q[4];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_9__gray_code_y q[6],q[5],q[4],q[3];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_11__block_wrapper_9__identity_1 q[0],q[1],q[2],q[3];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_13__gray_code_y q[6],q[5],q[4],q[3],q[2];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_15__block_wrapper_13__identity_1 q[0],q[1],q[2];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_17__gray_code_y q[6],q[5],q[4],q[3],q[2],q[1];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_19__block_wrapper_17__identity_1 q[0],q[1];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];
inplace_prepare_state__inplace_prepare_amplitudes__approximate_prepare_amplitudes__full_multiplex_gray_code__block_wrapper_23__block_wrapper_21__gray_code_y q[6],q[5],q[4],q[3],q[2],q[1],q[0];
main__identity q[0],q[1],q[2],q[3],q[4],q[5],q[6];